name = "provisiontestcfrs-app"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "CFR_USERS"
id = "4813e30205bf4c57944e15c5797bd353"

[[kv_namespaces]]
binding = "CFR_DATA"
id = "405e7c5dccc04072850c84f945c6722b"
