name = "eccleshallcfrs-app"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "CFR_USERS"
id = "fcfebe7bf9ea43daa2eb48965d4cfb19"

[[kv_namespaces]]
binding = "CFR_DATA"
id = "8848e48f5a004647afb6973c78093f22"
